server:
  port: 8078

spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: http://localhost:8848
      username: nacos
      password: nacos
    gateway:
      routes:
        - id: book-service
          uri: lb://order-service
          predicates:
            - name: Path
              args:
                pattern: /order/**
          filters:
            - StripPrefix=2
        - id: user-service
          uri: lb://user-service
          predicates:
            - name: Path
              args:
                pattern: /user/**
          filters:
            - StripPrefix=2

management:
  endpoints:
    web:
      exposure:
        include: "*"